add_rust_dashmap_crate Added dashmap crate version 5.4.0
compiler-explorer/infra pull request #1019
Opened 2023-05-31 16:29 UTC by thatmarkenglishguy

![](https://media.giphy.com/media/sRKg9r2YWeCTG5JTTo/giphy-downsized.gif)
Followed instructions in docs/adding_rust_crates.md.

This is the partner PR to

2023-06-02 13:11 UTC, mattgodbolt requested changes
You seem to have moved a bunch of other things around/formatted the file in some way. While I'm not against that in principle; I'd prefer to automate that and separate it from the addition of new functionality. Can you update to only have the dashmap addition please?

2023-06-02 13:36 UTC, partouf commented
> You seem to have moved a bunch of other things around/formatted the file in some way. While I'm not against that in principle; I'd prefer to automate that and separate it from the addition of new functionality. Can you update to only have the dashmap addition please?

If the documentation was followed, it is exactly that, we have formatting if added "correctly". So this is basically just undoing the mess that was made by someone else. (probably me)

The reason I didn't reply to this yet is because we're still blocked by https://github.com/compiler-explorer/infra/issues/977 and we can't merge this before that gets fixed

2023-06-02 13:37 UTC, mattgodbolt commented
OIC thanks Partouf....I think I'd like to move the formatting to a regular yaml formatter in pre-commit hooks so it's consistently applied, if that works for you?

2023-08-25 12:11 UTC, partouf approved these changes

2023-08-25 12:11 UTC, merged