Changes made in cpp.yaml to install hexagon-clang++
compiler-explorer/infra pull request #1061
Opened 2023-08-01 06:17 UTC by quic-rvarghes

Some changes have been made to cpp.yaml to allow hexagon-clang++ compiler to be installed.

2023-08-03 02:50 UTC, mattgodbolt requested changes

2023-08-03 06:25 UTC, quic-rvarghes commented
Hey @mattgodbolt , I have made the suggested changes. Hopefully, everything is all right now.

2023-08-07 04:33 UTC, abhikran-quic commented
Hi @mattgodbolt , Could you please review this PR ?

2023-08-07 12:37 UTC, mattgodbolt commented
Will get to this tonight: sorry for the delay!

2023-08-07 23:08 UTC, mattgodbolt approved these changes
LGTM - sorry it took so long! Will merge and confirm this installs OK!

2023-08-07 23:10 UTC, merged

2023-08-07 23:15 UTC, mattgodbolt commented
Compiled and installed ok - again thanks for your patience.
```
2023-08-07 23:15:34,371 lib.ce_install  INFO     compilers/c++/clang-hexagon 16.0.5 installed OK
```

2023-08-08 03:35 UTC, abhikran-quic commented
Thank you @mattgodbolt for your help! :)