[MS] Add C compilers and disable python
compiler-explorer/infra pull request #465
Opened 2021-02-20 17:11 UTC by partouf

Would fix https://github.com/compiler-explorer/compiler-explorer/issues/1371

Based on mstodo branch.

2021-02-22 18:39 UTC, strega-nil requested changes

2021-02-22 18:39 UTC, strega-nil commented on windows/Msvce.psm1
> +  if ($GenerateClocal -eq $true) {
```suggestion
  if ($CProperties) {
```

2021-02-22 18:39 UTC, strega-nil commented on windows/Msvce.psm1
> +    [bool]$GenerateClocal,
```suggestion
    [switch]$CProperties,
```

2021-02-22 18:39 UTC, strega-nil commented on windows/Msvce.psm1
> +  }
```suggestion
  } else {
      $compilerIdPrefix = ''
      $propertiesFilename = 'c++.local.properties'
  }
```

2021-02-22 18:39 UTC, strega-nil commented on windows/Msvce.psm1
> +  $propertiesFilename = 'c++.local.properties'
```suggestion
```

2021-02-22 18:39 UTC, strega-nil commented on windows/Msvce.psm1
> +  if ($GenerateClocal -eq $false) {
```suggestion
  if (-not $CProperties) {
```

2021-02-22 18:39 UTC, strega-nil commented on windows/Msvce.psm1
> +    -GenerateClocal $false `
```suggestion
```

2021-02-22 18:39 UTC, strega-nil commented on windows/Msvce.psm1
> +    -GenerateClocal $true `
```suggestion
    -CProperties `
```

2021-02-22 18:39 UTC, strega-nil commented on windows/Msvce.psm1
> +  Write-Verbose 'Installing MSVCE c++ configuration file'
```suggestion
  Write-Verbose 'Installing MSVCE C++ configuration file'
```

2021-02-22 18:39 UTC, strega-nil commented on windows/Msvce.psm1
> +  Write-Verbose 'Installing MSVCE c configuration file'
```suggestion
  Write-Verbose 'Installing MSVCE C configuration file'
```

2021-02-22 18:39 UTC, strega-nil commented on windows/Msvce.psm1
> +If true, generate a c.local.properties file instead of for c++.
```suggestion
.PARAMETER CProperties

Generate c.local.properties as opposed to c++.local.properties.
```

2021-02-22 18:39 UTC, strega-nil commented on windows/Msvce.psm1
> +    [Parameter(Mandatory=$true)]
```suggestion
    [Parameter()]
```

2021-02-23 01:56 UTC, partouf commented
Thanks for the review @strega-nil !
Suggestions make sense, will apply and test tomorrow.

2021-02-24 00:25 UTC, partouf commented
merged everything, worked as advertised

2021-02-24 00:25 UTC, merged