[MS] Use and support newer CE commit
compiler-explorer/infra pull request #469
Opened 2021-02-24 01:34 UTC by partouf

TODO
* [ ] Start CE with the right node params

Probably something about changing https://github.com/compiler-explorer/infra/blob/main/windows/files/Dockerfile.template#L44 to include `-r esm` ? Like we do here https://github.com/compiler-explorer/infra/blob/main/init/start.sh#L76

2021-02-24 01:35 UTC, partouf commented
Draft/todo's left

2021-02-24 01:45 UTC, partouf commented
Basically works. Want to test some more.

2021-02-24 02:07 UTC, partouf commented
Things also fixed in this:
* Disables demangler for C, as I got errors when I did something more than square()
* Explicitly sets `supportsBinary=falses` - not exactly sure what's the difference here between C and C++, but in C++ that was already disabled and for C it was not?

2021-02-24 18:40 UTC, strega-nil commented
@partouf yeah, the demangler is only for C++
also, what does `supportsBinary` do?

2021-02-24 18:59 UTC, partouf commented
It's for the "Output" - "Compile to binary" option, which links instead of just showing assembly.

2021-02-25 09:18 UTC, partouf commented
New todo:
* Make undname not use latest MSVC, but a more stable version

2021-02-26 21:19 UTC, partouf commented
Made changes to not use Latest for undname but the version before that.
(I really really really do not like `do {} while/until`, so I never use it in other languages and thus this code is a bit of a mess)

2021-02-26 21:53 UTC, partouf commented
Will await PR from MS where latest is actually in the json to test this just in case.

2021-03-01 16:55 UTC, strega-nil requested changes

2021-03-01 16:55 UTC, strega-nil commented on windows/Msvce.psm1
> +  }
```suggestion
  function GetLastStableVersion {
    Param([string[]] $Versions)
    $stableVersions = $Versions | Where-Object { -not (Get-MsvceToolsetPrettyName $_).Contains('latest') }
    $stableVersions[-1]
  }
```

2021-03-04 21:36 UTC, partouf commented
Seems to work. Thanks @strega-nil !

2021-03-04 21:36 UTC, merged