added typescript native compiler
compiler-explorer/infra pull request #690
Opened 2022-03-16 22:49 UTC by ODuzhar

Added typescript native compiler

2022-03-17 07:26 UTC, matsjla requested changes

2022-03-21 16:48 UTC, ASDAlexander77 commented on bin/yaml/typescript.yaml
> +    dir: tsc
I have updated file to support versions and changed name

2022-03-22 02:55 UTC, mattgodbolt approved these changes
Thanks: sorry it's taken so long for me to get to this

2022-03-22 02:55 UTC, merged

2022-03-22 02:58 UTC, mattgodbolt commented
Installed nicely:
```
$ /opt/compiler-explorer/tsc-0.0-pre-alpha20/bin/tsc --version
LLVM (http://llvm.org/):
  LLVM version 13.0.0
  Optimized build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver1
```