Add the jakt programming language
compiler-explorer/infra pull request #765
Opened 2022-07-06 15:00 UTC by TrMen

Jakt does not currently (and for the forseeable future) provide any
precompiled binaries. So the compiler needs to be build from source.

The way I did it is a bit of a hack, since I didn't see how I could install a
compiler from GitHub, so I reused the GitHub installation for libraries
and manually installed them to a different path than libs/

There are two compilers, a rust-based one that's build using cargo, and
then a selfhosted compiler that's build using the rust-based compiler
(for now).

This installs two compilers as one, since we need our rust-based
compiler to compile the selfhosted compiler.

2022-07-06 15:01 UTC, matsjla requested changes
Should probably have this in misc-builder rather than building in infra

2022-07-06 17:15 UTC, TrMen commented
> Should probably have this in misc-builder rather than building in infra

Makes sense. I added something in https://github.com/compiler-explorer/misc-builder/pull/40. 

I'm a little unclear how these things all fit together, so can you please check if this PR and that one together make sense?

2022-07-07 11:50 UTC, partouf commented
This should now be possible to install. 

(bin/ce_install --enable nightly install jakt)

2022-07-07 15:32 UTC, TrMen commented
Ok, I switched it to use `type: nightly` so it downloads the file from s3 with the correct date attached. I think this works now. Running `bin/ce_install --enable nightly install jakt` locally, then running ce locally with the `amazon` configurations from https://github.com/compiler-explorer/compiler-explorer/pull/3845 seems to work. But to be honest, I'm still a little hazy on how the different folders and options all interact. Does this configuration good to you?

2022-07-07 15:37 UTC, partouf commented
I can check the folders tonight.. i think.. otherwise I’ll get back to you this weekend

2022-07-07 15:38 UTC, merged